version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    # image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"  # For Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker inside Jenkins
    environment:
      JENKINS_OPTS: --httpPort=8080

volumes:
  jenkins_home:
